// brings all modules

import '../components/eit-counter.js'
import '../components/hello-world.js'
import '../components/feedback-element.js'
import '../components/timestamp-to-date.js'
import '../components/eit-input.js'
import '../components/componente-titulo.js'
import '../components/componente-plantilla.js'
import '../components/componente-agregar-contacto.js'
import '../components/tags-list.js'
import '../components/slot-intro.js'
import '../components/menu-overlay.js'
import '../components/pagination-simulator.js'
import '../components/eit-switch.js'
